#!/bin/bash
VOLT=""

if [ ! -f /usr/lib/pocketchip-batt/warn05 ] && [ ! $(cat /usr/lib/pocketchip-batt/charging) = "0" ]; then

  while [ -z "$VOLT" ]
  do
    VOLT=$(cat /usr/lib/pocketchip-batt/voltage)
  done

  if [ $(echo " $VOLT < 3350" | bc ) -eq 1 ]; then
    DISPLAY=:0 pocket-exit-5
    touch /usr/lib/pocketchip-batt/warn05
  else
    rm /usr/lib/pocketchip-batt/warn05
  fi

fi
