#!/bin/sh

set -ue

VOLTAGE=$(battery.sh | sed -En 's/Battery voltage = ([0-9]+).*/\1/p')
CHARGING=$(battery.sh | sed -n s/CHARG_IND=//p)

echo "${VOLTAGE:-3700}" > /usr/lib/pocketchip-batt/voltage
echo "${CHARGING:-0}" > /usr/lib/pocketchip-batt/charging
